### ISSUE TITLE
Attempt to console gives undefined global const

### ISSUE THREAD

**Issue by venix1** [gtmanfred/hammercloud#7]
(hammercloud) ~/projects/rax/hammercloud $ hc --console aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
Traceback (most recent call last):
  File ".pyenv/versions/hammercloud/bin/hc", line 10, in <module>
    sys.exit(main())
  File "projects/rax/hammercloud/hammercloud/hammercloud.py", line 99, in main
    ret = handle(servers)
  File "projects/rax/hammercloud/hammercloud/handle.py", line 59, in handle
    shell.exec_console(console_url, logininfo)
  File "projects/rax/hammercloud/hammercloud/shell/**init**.py", line 88, in exec_console
    '{0}Device:{1} {2}'.format(const.BLUE,
NameError: global name 'const' is not defined

Looks like this may be a simple as a missing import in hammercloud/hammercloud/shell/**init**.py

`from hammercloud import Constants as const`

**Comment by KaiSforza** [comment]
It seems we're running into some fun with modules.

What version of python are you using, @venix1?

**Comment by venix1** [comment]
2.7.10
